name: Python CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

  # Manually trigger upload job with workflow_dispatch
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag for the Docker image (default: latest)'
        required: false
        default: 'latest'

jobs:
  # Job 1: Build and Test (auto-triggered on push)
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest
      run: |
        python -m unittest discover

  # Job 2: Docker Image Creation and Upload (manual trigger only)
  upload-and-deploy:
    needs: build-and-test  # Ensure this runs only after 'build_and_test' is successful
    if: ${{ (github.event_name == 'workflow_dispatch') }} 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Store DockerHub username in secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Store DockerHub password in secrets

      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/breast-cancer-api:${{ github.event.inputs.image_tag }} .

      - name: Push Docker image to DockerHub
        run: |
          docker push your-dockerhub-username/breast-cancer-api:${{ github.event.inputs.image_tag }}